---
- name: Install and start Apache web server
  hosts: webservers
  become: yes

  tasks:
    - name: Install Apache package
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a custom homepage
      copy:
        content: "Welcome to my Apache server!"
        dest: /var/www/html/index.html

